// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_librerias_paco.Models;

#nullable disable

namespace api_librerias_paco.Migrations
{
    [DbContext(typeof(LibreriaContext))]
    [Migration("20230222174016_nombreMigracion")]
    partial class nombreMigracion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("api_librerias_paco.Models.Clientes", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<string>("Contraseña")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("saldo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("api_librerias_paco.Models.LibroCliente", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<int?>("ClientesId")
                        .HasColumnType("int");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int?>("IdLibro")
                        .HasColumnType("int");

                    b.Property<int?>("LibrosId")
                        .HasColumnType("int");

                    b.Property<string>("NombreLibro")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientesId");

                    b.HasIndex("LibrosId");

                    b.ToTable("LibrosCliente");
                });

            modelBuilder.Entity("api_librerias_paco.Models.Libros", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<string>("Autor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaPublicacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Paginas")
                        .HasColumnType("int");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("enVenta")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Libro");
                });

            modelBuilder.Entity("api_librerias_paco.Models.Tiendas", b =>
                {
                    b.Property<int?>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("id"), 1L, 1);

                    b.Property<string>("calle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("codigopostal")
                        .HasColumnType("int");

                    b.Property<string>("comunidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("localidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("trabajadores")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Tiendas");
                });

            modelBuilder.Entity("api_librerias_paco.Models.LibroCliente", b =>
                {
                    b.HasOne("api_librerias_paco.Models.Clientes", "Clientes")
                        .WithMany()
                        .HasForeignKey("ClientesId");

                    b.HasOne("api_librerias_paco.Models.Libros", "Libros")
                        .WithMany()
                        .HasForeignKey("LibrosId");

                    b.Navigation("Clientes");

                    b.Navigation("Libros");
                });
#pragma warning restore 612, 618
        }
    }
}
